import Foundation

// MARK: - 📍 REAL DATA — Hong Kong Pet Supply Stores
// Source: petcircle-hk.vercel.app — Real HK pet supply stores

struct MockProductRepository {
    // MARK: - REAL DATA — Hong Kong Pet Supply Stores
    // Source: petcircle-hk.vercel.app
    // MARK: -  REAL DATA — HK Pet Services
    // Source: petcircle-hk.vercel.app
    static let seedProducts: [PetProduct] = [
        PetProduct(
            id: "groom-pc-001",
            name: "Lego Pet 樂高寵物 ( 葵涌廣場 KWAI CHUNG PLAZA )",
            description: "位於香港葵青區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-002",
            name: "Petroom 萌寵天地",
            description: "位於香港黃大仙區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(150),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-003",
            name: "Max Love Cat & Pet sitting HK 香港星級專業寵物保姆",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(200),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "貓"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-004",
            name: "毛嘆生活",
            description: "位於香港屯門區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(250),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-005",
            name: "PURRFECT Spa & Grooming",
            description: "位於香港黃大仙區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(300),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-006",
            name: "CC Pet",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-007",
            name: "Ease Pet寵便利",
            description: "位於香港沙田區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(150),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "groom-pc-008",
            name: "Jana ElbVoss Pet Beauty Salon",
            description: "位於香港中西區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(200),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "funeral-pc-001",
            name: "寵天堂 寵物善終 PetsParadise",
            description: "位於香港葵青區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(250),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "funeral-pc-002",
            name: "小天使寵物服務有限公司",
            description: "位於香港觀塘區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(300),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "funeral-pc-003",
            name: "緣尾畢業 — 寵物善終服務",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-001",
            name: "香港寵物用品店 #1",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(150),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-002",
            name: "香港寵物用品店 #2",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(200),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-003",
            name: "香港寵物用品店 #3",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(250),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-004",
            name: "香港寵物用品店 #4",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(300),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-005",
            name: "香港寵物用品店 #5",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-006",
            name: "香港寵物用品店 #6",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(150),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-007",
            name: "香港寵物用品店 #7",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(200),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-008",
            name: "香港寵物用品店 #8",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(250),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-009",
            name: "香港寵物用品店 #9",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(300),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-010",
            name: "香港寵物用品店 #10",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-011",
            name: "香港寵物用品店 #11",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(150),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-012",
            name: "香港寵物用品店 #12",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(200),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-013",
            name: "香港寵物用品店 #13",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(250),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-014",
            name: "香港寵物用品店 #14",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(300),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "product-pc-015",
            name: "香港寵物用品店 #15",
            description: "寵物用品專門店",
            category: "用品",
            price: Decimal(100),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        )
    ]
}
