import Foundation

// MARK: - 📍 REAL DATA — Hong Kong Pet Supply Stores
// Source: petcircle-hk.vercel.app — Real HK pet supply stores

struct MockProductRepository {
    // MARK: - REAL DATA — Hong Kong Pet Supply Stores
    // Source: petcircle-hk.vercel.app
    // MARK: -  REAL DATA — HK Pet Services
    // Source: petcircle-hk.vercel.app
    // MARK: - REAL DATA — HK Pet Services
    // Source: petcircle-hk.vercel.app — 170 businesses (supplies, grooming, funeral)
    static let seedProducts: [PetProduct] = [
        PetProduct(
            id: "svc-supp-0000",
            name: "MYZOO動物緣",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0001",
            name: "Lego Pet 樂高寵物 (又新街 Yau San Street)",
            description: "位於香港元朗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0002",
            name: "天下貓貓一樣貓（元朗站）",
            description: "位於香港元朗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0003",
            name: "Chill•愛貓 Chill Love Cats",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0004",
            name: "天下貓貓一樣貓(大圍站)",
            description: "位於香港沙田區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0005",
            name: "PetsOrder 寵物網 ( Fanling 粉嶺 )",
            description: "位於香港北區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0006",
            name: "PetsOrder 寵物網 (Hoi Pa St. 海壩街)",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0007",
            name: "Lego Pet 樂高寵物 ( 葵涌廣場 KWAI CHUNG PLAZA )",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0008",
            name: "Lego Pet 樂高寵物 ( TMT Plaza 屯門市廣場)",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0009",
            name: "Petroom 萌寵天地",
            description: "位於香港黃大仙區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0010",
            name: "Lego Pet 樂高寵物 (觀塘 Kwun Tong)",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0011",
            name: "One Woof Club",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0012",
            name: "Furbabies' Meal 毛孩膳食｜寵物鮮食包",
            description: "位於香港沙田區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0013",
            name: "Hidden Gems",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0014",
            name: "毛嘆生活",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0015",
            name: "天下貓貓一樣貓(天后站)",
            description: "位於香港灣仔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0016",
            name: "CC Pet",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0017",
            name: "好街坊寵物用品",
            description: "位於香港元朗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0018",
            name: "Furry Green Fresh Pet Food 惜食寵物鮮食",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0019",
            name: "寵物店 [ First Pet ]",
            description: "位於香港九龍城區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0020",
            name: "油麻地活靈寵物用品",
            description: "位於香港油尖旺區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0021",
            name: "Ease Pet寵便利",
            description: "位於香港沙田區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0022",
            name: "Pet Pet Homies",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0023",
            name: "Dog Inn",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0024",
            name: "PET IN CHARGE",
            description: "位於香港灣仔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0025",
            name: "Pet Pet Home | 荃灣店",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0026",
            name: "Pet n' wooo 寵物角度",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0027",
            name: "Dog Romance",
            description: "位於香港九龍城區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0028",
            name: "I-Neko 喵犬会社",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0029",
            name: "Pawlistic Kitchen 寵食療坊 (Fresh Pet Food 寵物鮮食）",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0030",
            name: "Hidden Gems",
            description: "位於香港西貢區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0031",
            name: "LittleLand",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0032",
            name: "Life-In Touch Woo Meow 正汪型純寵",
            description: "位於香港元朗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0033",
            name: "Happy Paws 腳印印",
            description: "位於香港西貢區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0034",
            name: "DD Dog Kennel 大叔犬舍",
            description: "位於香港元朗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0035",
            name: "良心貓舍",
            description: "位於香港北區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0036",
            name: "HOLY CAP",
            description: "位於香港灣仔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0037",
            name: "Hunter Pet Shop 肯特利寵物專門店",
            description: "位於香港深水埗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0038",
            name: "FatFatPetShop 肥肥寵物用品店",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0039",
            name: "寵物用品店 - 毛店長",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0040",
            name: "FURRYTALE",
            description: "位於香港大埔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0041",
            name: "FITMIN HONG KONG - Snoop Pet Shop",
            description: "位於香港大埔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0042",
            name: "THE GARDEN OF EDEN PET SHOP",
            description: "位於香港港島東區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0043",
            name: "Pet Box 寵物鮮食盒",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0044",
            name: "寵芝靈",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0045",
            name: "Good Pet Naturally",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0046",
            name: "Doggie.hk寵物坊",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0047",
            name: "迷彩爬取",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0048",
            name: "叮叮寵物站 Ding Ding pet shop",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0049",
            name: "Ichi-Inu 犬．一",
            description: "位於香港油尖旺區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0050",
            name: "Guangdong Lingzhi pet supplies trading companies",
            description: "位於香港中西區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0051",
            name: "Essential Foods Hong Kong",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0052",
            name: "ROIKEE.STORE",
            description: "位於香港灣仔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0053",
            name: "Prime Pet Zone",
            description: "位於香港南區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0054",
            name: "貓盧貓舍Cat Lo Shop",
            description: "位於香港深水埗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0055",
            name: "BUDDY CAT",
            description: "位於香港油尖旺區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0056",
            name: "Meowthings寵物店",
            description: "位於香港深水埗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0057",
            name: "Petvila",
            description: "位於香港深水埗區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0058",
            name: "FluffandFashion",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0059",
            name: "招財貓舍 LUCKY CAT SHOP",
            description: "位於香港觀塘區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0060",
            name: "Hunter Pet Shop 肯特利寵物專門店",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0061",
            name: "達利國際有限公司",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0062",
            name: "CAT PLUS 「貓+」貓咪用品專門店",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0063",
            name: "Topnotch-宏一國際– 寵物用品",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0064",
            name: "天然國際寵物有限公司",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0065",
            name: "Grandmaster Cat 貓代宗師",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0066",
            name: "天豐貿易公司B2CshopHK",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0067",
            name: "Cat Elf",
            description: "位於香港葵青區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0068",
            name: "Pet Line 寵寵線 (屯門巿廣場店)",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0069",
            name: "寵物用品專門店",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0070",
            name: "CAT PLUS 「貓+」貓咪用品專門店 (大埔分店)",
            description: "位於香港大埔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0071",
            name: "大埔公平行 寵物用品",
            description: "位於香港大埔區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0072",
            name: "Pet-a-Pet",
            description: "位於香港香港嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0073",
            name: "Lantau Pet 寵物用品速遞",
            description: "位於香港荃灣區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-supp-0074",
            name: "Champwin - PetMeHome | HK Pet Supply",
            description: "位於香港屯門區嘅寵物用品店，提供寵物食品、用品及配件。",
            category: "用品",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物用品"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0075",
            name: "Lego Pet 樂高寵物 ( 葵涌廣場 KWAI CHUNG PLAZA )",
            description: "位於香港葵青區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0076",
            name: "Petroom 萌寵天地",
            description: "位於香港黃大仙區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0077",
            name: "Max Love Cat u0026 Pet sitting HK 香港星級專業寵物保姆",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "貓"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0078",
            name: "毛嘆生活",
            description: "位於香港屯門區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0079",
            name: "PURRFECT Spa u0026 Grooming",
            description: "位於香港黃大仙區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0080",
            name: "CC Pet",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0081",
            name: "Ease Pet寵便利",
            description: "位於香港沙田區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0082",
            name: "Jana ElbVoss Pet Beauty Salon",
            description: "位於香港中西區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0083",
            name: "Mu0026C PET",
            description: "位於香港沙田區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0084",
            name: "Soapy Pawsie | Hydrotherapy | Grooming | Products",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0085",
            name: "Dog Inn",
            description: "位於香港觀塘區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0086",
            name: "Tinja Pets Beauty 寵物美容（Prince Edward)",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0087",
            name: "倆．Chillax.Grooming寵物美容",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0088",
            name: "Pet Pet Salon",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0089",
            name: "Pet Pet Home | 荃灣店",
            description: "位於香港荃灣區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0090",
            name: "Pet n' wooo 寵物角度",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0091",
            name: "國際專業寵物美容學院",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0092",
            name: "Pawsmetic Spa u0026 Wellness 醫護級寵物美容",
            description: "位於香港油尖旺區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0093",
            name: "Dog Romance",
            description: "位於香港九龍城區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0094",
            name: "Happy Paws 腳印印",
            description: "位於香港西貢區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0095",
            name: "FURRYTALE",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0096",
            name: "扮靚靚犬隻美容",
            description: "位於香港觀塘區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0097",
            name: "Spaw Station",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0098",
            name: "FUWA - FUWA ペット・グルーミングサロン Pet Grooming",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0099",
            name: "Big Paws Pet Salon u0026 Academy-毛毛波士",
            description: "位於香港九龍城區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0100",
            name: "DnD 寵物水療(土瓜灣)",
            description: "位於香港九龍城區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0101",
            name: "笨蕉寵物屋",
            description: "位於香港北區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0102",
            name: "Morio Pet Company",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0103",
            name: "Furrari Grooming",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0104",
            name: "剪毛毛寵物美容中心",
            description: "位於香港屯門區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0105",
            name: "Waku Pet House",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0106",
            name: "LittleMore Pet Grooming",
            description: "位於香港西貢區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0107",
            name: "Cat Boss Pet Grooming",
            description: "位於香港油尖旺區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "貓"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0108",
            name: "逍閑寵物美容",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0109",
            name: "Winny Pet House",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0110",
            name: "愛犬匯寵物水療中心",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0111",
            name: "仟仟寵物美容",
            description: "位於香港九龍城區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0112",
            name: "Pet Space Discovery Bay",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0113",
            name: "GO GO BATH PET CO",
            description: "位於香港港島東區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0114",
            name: "Cutie pets store",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0115",
            name: "VV Pet Pet 專業寵物美容",
            description: "位於香港港島東區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0116",
            name: "Little Primo 略懂皮毛",
            description: "位於香港觀塘區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0117",
            name: "寵伴工房 Mate Pet Kobo",
            description: "位於香港深水埗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0118",
            name: "貓犬美容寵物舍",
            description: "位於香港黃大仙區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "貓", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0119",
            name: "I Love Pet Pet",
            description: "位於香港油尖旺區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0120",
            name: "Mayu0026David寵物美容",
            description: "位於香港大埔區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0121",
            name: "pet secret 寵密 － 沙田寵物美容店",
            description: "位於香港沙田區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0122",
            name: "Rolls pet salon 笑爺仔寵物美容",
            description: "位於香港元朗區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0123",
            name: "Doggie Stylist Grooming u0026 Spa",
            description: "位於香港油尖旺區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0124",
            name: "URBAN PETŌ",
            description: "位於香港西貢區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0125",
            name: "狗仔隊寵物美容店",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0126",
            name: "寵寵熊寵物美容",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0127",
            name: "壹壹寵物",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0128",
            name: "Jolly Pets",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0129",
            name: "Fluffy Grooming 寵物美容生活體驗館",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0130",
            name: "Bu’s Pet Grooming Salon 寶之淋寵物美容坊",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0131",
            name: "寵物溫泉",
            description: "位於香港大埔區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0132",
            name: "靈靈狗寵物美容",
            description: "位於香港大埔區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0133",
            name: "小怪獸寵物美容 Little Monster Grooming",
            description: "位於香港屯門區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0134",
            name: "Pet minions",
            description: "位於香港荃灣區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0135",
            name: "三色貓寵物美容專門店",
            description: "位於香港灣仔區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "貓"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0136",
            name: "寵信 Favourite Pet",
            description: "位於香港西貢區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0137",
            name: "毛優小店",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0138",
            name: "Bark u0026 Bubbles Pet Grooming",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0139",
            name: "V.I. Pet Grooming Service",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0140",
            name: "Doglish Grooming u0026 Spa",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "狗", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0141",
            name: "Fear Free Pets Grooming 無恐懼寵物美容",
            description: "位於香港香港嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0142",
            name: "Fluffy Flossy Herbal SPA u0026 Grooming",
            description: "位於香港北區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容", "SPA"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0143",
            name: "花花寵物屋",
            description: "位於香港北區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0144",
            name: "BOOM BOOM PET CARE",
            description: "位於香港北區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-groo-0145",
            name: "穎迎寵物",
            description: "位於香港北區嘅寵物美容店，提供狗貓洗澡、剪毛及護理服務。",
            category: "美容",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物美容"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0146",
            name: "寵天堂 寵物善終 PetsParadise",
            description: "位於香港葵青區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0147",
            name: "小天使寵物服務有限公司",
            description: "位於香港觀塘區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0148",
            name: "緣尾畢業 — 寵物善終服務",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0149",
            name: "常伴心寵物善終服務 Forever in Heart",
            description: "位於香港深水埗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0150",
            name: "小寵物紀念館（銅鑼灣區寵物善終服務）",
            description: "位於香港灣仔區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0151",
            name: "毛孩守護天國總辦事處（合法寵物靈灰安置所）",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0152",
            name: "寵之天國寵物善終服務",
            description: "位於香港觀塘區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0153",
            name: "情永在寵物善終服務",
            description: "位於香港葵青區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0154",
            name: "香港寵物紀念館 (24/7 寵物善終) Hong Kong Pet Memorial",
            description: "位於香港深水埗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0155",
            name: "寵之花園元朗寵物善終服務",
            description: "位於香港元朗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0156",
            name: "RESOUL| 寵物善終服務",
            description: "位於香港南區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0157",
            name: "Petmento 寵物善終 紀念晶石",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0158",
            name: "再見寵兒｜寵物善終｜寵物火化｜寵物水化｜寵物靈堂",
            description: "位於香港葵青區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0159",
            name: "寵愛無限寵物善終服務",
            description: "位於香港葵青區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0160",
            name: "TLC寵樂緣(牛頭角店)",
            description: "位於香港觀塘區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0161",
            name: "寵之家寵物善終服務",
            description: "位於香港深水埗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0162",
            name: "元朗逢吉鄉路DD 107 LOT 1207",
            description: "位於香港元朗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0163",
            name: "彩虹橋寵物善終服務有限公司",
            description: "位於香港元朗區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0164",
            name: "寵物善終（香港）",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0165",
            name: "回歸自然 | 寵物善終服務",
            description: "位於香港北區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0166",
            name: "緣善寵物服務集團有限公司-灣仔分店",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0167",
            name: "寵寵畢業禮 寵物善終服務（骨灰盫）",
            description: "位於香港油尖旺區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0168",
            name: "忘不了寵物善終",
            description: "位於香港香港嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
        PetProduct(
            id: "svc-fune-0169",
            name: "Hong Kong Pet Urn",
            description: "位於香港荃灣區嘅寵物善終服務，提供寵物火化、善終及骨灰安置服務。",
            category: "善終",
            price: Decimal(0),
            currency: "HKD",
            clinicId: nil,
            affiliateURL: nil,
            imageURL: nil,
            tags: ["寵物善終"],
            createdAt: Date(timeIntervalSince1970: 1_749_200_000)
        ),
    ]
}
