import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {analyzeInventory, expectedAvailability, listFirestoreClinics, parseOptions, runMigration} from "./restore_hk_clinic_hours_v3_pending.mjs";
const paths={catalog:"catalog/hk_clinics_v1.json",v1Hours:"catalog/hk_clinic_hours_v1.json",v2Hours:"catalog/hk_clinic_hours_v2.pending.json",pending:"catalog/hk_clinic_hours_v3.pending.json"},clone=v=>JSON.parse(JSON.stringify(v));
async function values(){const read=p=>readFile(new URL(`../${p}`,import.meta.url),"utf8").then(JSON.parse);return {catalog:await read(paths.catalog),v1Hours:await read(paths.v1Hours),v2Hours:await read(paths.v2Hours),pending:await read(paths.pending)};}
function inventory(v,v3="absent"){const e1=new Map(v.v1Hours.clinics.map(c=>[c.clinicID,expectedAvailability(v.v1Hours,c,"hk-clinic-hours-v1-2026-07-30")])),e2=new Map(v.v2Hours.clinics.map(c=>[c.clinicID,expectedAvailability(v.v2Hours,c)])),e3=new Map(v.pending.clinics.map(c=>[c.clinicID,expectedAvailability(v.pending,c)]));const docs=v.catalog.clinics.map((c,i)=>({id:c.id,updateTime:`2026-09-01T00:00:${String(i%60).padStart(2,"0")}.000Z`,fields:{name:c.name,status:"approved",catalogRegion:"HK",region:"HK",...(e1.has(c.id)?{availability:e1.get(c.id)}:e2.has(c.id)?{availability:e2.get(c.id)}:v3==="exact"&&e3.has(c.id)?{availability:e3.get(c.id)}:{})},raw:{name:`projects/vetmap-app/databases/(default)/documents/clinics/${c.id}`,updateTime:`2026-09-01T00:00:${String(i%60).padStart(2,"0")}.000Z`}}));docs.push({id:"vetmap-demo-clinic",updateTime:"2026-09-01T00:00:59.000Z",fields:{name:"VetMap 示範診所（非真實商戶）",status:"approved"},raw:{name:"projects/vetmap-app/databases/(default)/documents/clinics/vetmap-demo-clinic",updateTime:"2026-09-01T00:00:59.000Z"}});return docs;}
test("v3 dry-run preserves exact v1/v2 and apply verifies combined 33/14/19",async()=>{const v=await values();let docs=inventory(v),commits=0;const readJSON=async p=>clone(v[Object.keys(paths).find(k=>paths[k]===p)]),backup=async()=>({path:"backup.json",sha256:"a".repeat(64)});const dry=await runMigration({options:parseOptions([]),readJSON,listClinics:async()=>docs,writeBackup:backup});assert.deepEqual([dry.currentTotal,dry.current24Hours,dry.currentScheduled],[15,11,4]);const applied=await runMigration({options:parseOptions(["--apply"]),readJSON,listClinics:async()=>docs,writeBackup:backup,commit:async({writes})=>{commits+=1;for(const w of writes){const id=w.update.name.split("/").at(-1),clinic=v.pending.clinics.find(c=>c.clinicID===id);docs.find(d=>d.id===id).fields.availability=expectedAvailability(v.pending,clinic);}return {ok:true};}});assert.equal(commits,1);assert.deepEqual([applied.currentTotal,applied.current24Hours,applied.currentScheduled],[33,14,19]);});
test("prior drift, stray availability, partial v3, and identity drift fail closed",async()=>{const v=await values();const mutations=[d=>{d.find(x=>x.id===v.v1Hours.clinics[0].clinicID).fields.availability={};},d=>{d.find(x=>x.id===v.v2Hours.clinics[0].clinicID).fields.availability={};},d=>{d.find(x=>x.id==="vetmap-demo-clinic").fields.availability={};},d=>{d.find(x=>x.id===v.pending.clinics[0].clinicID).fields.availability=expectedAvailability(v.pending,v.pending.clinics[0]);},d=>{d[0].fields.name="wrong";}];for(const mutate of mutations){const docs=inventory(v);mutate(docs);assert.throws(()=>analyzeInventory(docs,v));}});
test("Firestore listing follows pagination",async()=>{let calls=0;const docs=await listFirestoreClinics({token:"x",fetchImpl:async()=>({ok:true,json:async()=>{calls+=1;return calls===1?{documents:[],nextPageToken:"two"}:{documents:[]};}})});assert.equal(docs.length,0);assert.equal(calls,2);});
test("Firestore listing decodes production scalar, geo, array, and map values",async()=>{const raw={name:"projects/vetmap-app/databases/(default)/documents/clinics/tw-test",updateTime:"2026-09-01T00:00:00.000Z",fields:{name:{stringValue:"Taiwan test"},score:{doubleValue:4.5},count:{integerValue:"7"},active:{booleanValue:true},nil:{nullValue:null},when:{timestampValue:"2026-09-01T00:00:00.000Z"},where:{geoPointValue:{latitude:25.03,longitude:121.56}},bytes:{bytesValue:"YWJj"},ref:{referenceValue:"projects/x/documents/y/z"},items:{arrayValue:{values:[{stringValue:"a"},{doubleValue:2.5}]}},nested:{mapValue:{fields:{ok:{booleanValue:true}}}}}};const docs=await listFirestoreClinics({token:"x",fetchImpl:async()=>({ok:true,json:async()=>({documents:[raw]})})});assert.deepEqual(docs[0].fields,{name:"Taiwan test",score:4.5,count:7,active:true,nil:null,when:"2026-09-01T00:00:00.000Z",where:{latitude:25.03,longitude:121.56},bytes:"YWJj",ref:"projects/x/documents/y/z",items:["a",2.5],nested:{ok:true}});});
test("inert non-HK extras are preserved while availability, HK masquerading, and missing prior IDs fail",async()=>{const v=await values();const inert={id:"tw-test-clinic",updateTime:"2026-09-01T00:00:00.000Z",fields:{name:"Taiwan test"},raw:{name:"projects/vetmap-app/databases/(default)/documents/clinics/tw-test-clinic",updateTime:"2026-09-01T00:00:00.000Z"}};const allowed=analyzeInventory([...inventory(v),inert],v);assert.equal(allowed.inertExtraCount,1);for(const mutate of [d=>{d.at(-1).fields.availability={};},d=>{d.at(-1).fields.catalogRegion="HK";},d=>{d.at(-1).fields.status="approved";},d=>d.filter(x=>x.id!==v.v1Hours.clinics[0].clinicID)]){const docs=[...inventory(v),clone(inert)];const result=mutate(docs);assert.throws(()=>analyzeInventory(result??docs,v),/inert extra|catalog clinic missing/);}});
test("actual demo schema is accepted but name, availability, and HK masquerading fail",async()=>{const v=await values();assert.doesNotThrow(()=>analyzeInventory(inventory(v),v));for(const mutate of [d=>{d.find(x=>x.id==="vetmap-demo-clinic").fields.name="wrong";},d=>{d.find(x=>x.id==="vetmap-demo-clinic").fields.availability={};},d=>{d.find(x=>x.id==="vetmap-demo-clinic").fields.region="HK";}]){const docs=inventory(v);mutate(docs);assert.throws(()=>analyzeInventory(docs,v),/demo/);}});
