import {createHash} from "node:crypto";
import {chmod, mkdir, readFile, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {validateHKClinicHoursV3Pending} from "./validate_hk_clinic_hours_v3_pending.mjs";

const ROOT="https://firestore.googleapis.com/v1/projects/vetmap-app/databases/(default)/documents", V1="hk-clinic-hours-v1-2026-07-30", DEMO="vetmap-demo-clinic", DEMO_NAME="VetMap 示範診所（非真實商戶）";
const PATHS={catalog:"catalog/hk_clinics_v1.json",v1Hours:"catalog/hk_clinic_hours_v1.json",v2Hours:"catalog/hk_clinic_hours_v2.pending.json",pending:"catalog/hk_clinic_hours_v3.pending.json"};
export function parseOptions(args){let apply=false,backupPath;for(let i=0;i<args.length;i+=1){if(args[i]==="--apply"&&!apply)apply=true;else if(args[i]==="--backup"&&!backupPath&&args[i+1]&&!args[i+1].startsWith("--"))backupPath=args[++i];else throw new Error("Usage: restore_hk_clinic_hours_v3_pending.mjs [--apply] [--backup PATH]");}return {apply,backupPath};}
const norm=(v)=>Array.isArray(v)?v.map(norm):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,norm(v[k])])):v;
export const sameJSON=(a,b)=>JSON.stringify(norm(a))===JSON.stringify(norm(b));
export const expectedAvailability=(m,c,id=m.migrationId)=>({schemaVersion:m.schemaVersion,migrationId:id,timeZoneIdentifier:m.timeZoneIdentifier,weeklyHours:c.weeklyHours,is24Hours:c.is24Hours,offersNightService:c.offersNightService,displayLabel:c.displayLabel,serviceNote:c.serviceNote,sourceURL:c.sourceURL,sourceName:c.sourceName,verifiedAt:new Date(m.verifiedAt).toISOString(),expiresAt:new Date(m.expiresAt).toISOString()});
const assert=(v,m)=>{if(!v)throw new Error(`v3 restore: ${m}`);};
export function analyzeInventory(documents,{catalog,v1Hours,v2Hours,pending},phase="pre"){
 const by=new Map();for(const d of documents){assert(!by.has(d.id),`duplicate document: ${d.id}`);by.set(d.id,d);}const cat=new Map(catalog.clinics.map(c=>[c.id,c]));assert(cat.size===179,"catalog must contain 179 HK clinics");assert(by.has(DEMO),`known demo document missing: ${DEMO}`);for(const [id,c] of cat){const d=by.get(id);assert(d,`catalog clinic missing: ${id}`);assert(d.fields.name===c.name&&d.fields.status==="approved"&&d.fields.catalogRegion==="HK"&&d.fields.region==="HK",`catalog identity drift: ${id}`);}const demo=by.get(DEMO);assert(demo&&demo.fields.name===DEMO_NAME&&demo.fields.status==="approved"&&!Object.hasOwn(demo.fields,"availability"),`demo identity drift: ${DEMO}`);for(const field of ["catalogRegion","region"])assert(demo.fields[field]===undefined||demo.fields[field]==="demo",`demo masquerades as unsafe region: ${DEMO}`);const inertExtras=[...by.values()].filter(d=>!cat.has(d.id)&&d.id!==DEMO);for(const extra of inertExtras){assert(!Object.hasOwn(extra.fields,"availability"),`inert extra has availability: ${extra.id}`);assert(extra.fields.status!=="approved"&&extra.fields.catalogRegion!=="HK"&&extra.fields.region!=="HK",`inert extra masquerades as HK/approved: ${extra.id}`);}
 const e1=new Map(v1Hours.clinics.map(c=>[c.clinicID,expectedAvailability(v1Hours,c,V1)])),e2=new Map(v2Hours.clinics.map(c=>[c.clinicID,expectedAvailability(v2Hours,c)])),e3=new Map(pending.clinics.map(c=>[c.clinicID,expectedAvailability(pending,c)])),all=new Map([...e1,...e2,...e3]);for(const [id,e] of [...e1,...e2])assert(sameJSON(by.get(id).fields.availability,e),`prior canonical availability drift: ${id}`);for(const d of documents)if(Object.hasOwn(d.fields,"availability")&&!all.has(d.id))throw new Error(`availability exists outside v1/v2/v3 planned IDs: ${d.id}`);
 const targets=pending.clinics.map(c=>{const d=by.get(c.clinicID);assert(d,`v3 target missing: ${c.clinicID}`);assert(d.updateTime&&d.raw?.updateTime===d.updateTime,`target updateTime missing: ${c.clinicID}`);assert(d.fields.name===c.expectedName&&d.fields.status==="approved"&&d.fields.catalogRegion==="HK"&&d.fields.region==="HK",`target identity drift: ${c.clinicID}`);return {...d,expected:e3.get(c.clinicID)};});const states=targets.map(t=>!Object.hasOwn(t.fields,"availability")?"absent":sameJSON(t.fields.availability,t.expected)?"exact":"different"),allExact=states.every(s=>s==="exact");assert(allExact||states.every(s=>s==="absent"),"v3 target availability must be all absent or all exact");if(phase==="post")assert(allExact,"post-state must contain v3 exactly");const total=e1.size+e2.size+(allExact?e3.size:0),open24=[...v1Hours.clinics,...v2Hours.clinics,...(allExact?pending.clinics:[])].filter(c=>c.is24Hours).length;if(phase==="post")assert(total===33&&open24===14&&total-open24===19,"combined post-state distribution must be 33/14/19");return {targets,allExact,inertExtraCount:inertExtras.length,current:{total,twentyFourHours:open24,scheduled:total-open24}};
}
function encode(v,k=""){if(k==="verifiedAt"||k==="expiresAt")return {timestampValue:new Date(v).toISOString()};if(v===null)return {nullValue:null};if(typeof v==="boolean")return {booleanValue:v};if(typeof v==="string")return {stringValue:v};if(typeof v==="number")return {integerValue:String(v)};if(Array.isArray(v))return {arrayValue:{values:v.map(x=>encode(x))}};return {mapValue:{fields:Object.fromEntries(Object.entries(v).map(([x,y])=>[x,encode(y,x)]))}};}
export const buildWrites=(targets)=>targets.map(t=>({update:{name:`projects/vetmap-app/databases/(default)/documents/clinics/${t.id}`,fields:{availability:encode(t.expected)}},updateMask:{fieldPaths:["availability"]},currentDocument:{updateTime:t.updateTime}}));
export async function writeBackupFile(docs,file){const payload=`${JSON.stringify({documents:docs},null,2)}\n`;await mkdir(path.dirname(file),{recursive:true});await writeFile(file,payload,{encoding:"utf8",mode:0o600});await chmod(file,0o600);return {path:file,sha256:createHash("sha256").update(payload).digest("hex")};}
export async function runMigration({options,readJSON,listClinics,writeBackup,commit,paths=PATHS}){const [catalog,v1Hours,v2Hours,pending]=await Promise.all(Object.values(paths).map(readJSON)),v={catalog,v1Hours,v2Hours,pending},coverage=validateHKClinicHoursV3Pending(v),before=analyzeInventory(await listClinics(),v),backup=await writeBackup(before.targets.map(t=>t.raw));assert(backup?.path&&/^[a-f0-9]{64}$/.test(backup.sha256??""),"backup must have path and SHA-256");const out={mode:options.apply?"apply":"dry-run",productionApplied:false,alreadyApplied:before.allExact,writeCount:before.allExact?0:pending.count,currentTotal:before.current.total,current24Hours:before.current.twentyFourHours,currentScheduled:before.current.scheduled,backupPath:backup.path,backupSHA256:backup.sha256,rollbackEvidence:`mode-0600 backup: ${backup.path}`,...coverage};if(!options.apply)return out;if(!before.allExact){const r=await commit({writes:buildWrites(before.targets)});assert(r?.ok,`atomic Firestore commit failed: HTTP ${r?.status??"unknown"}`);}const after=analyzeInventory(await listClinics(),v,"post");return {...out,productionApplied:true,currentTotal:after.current.total,current24Hours:after.current.twentyFourHours,currentScheduled:after.current.scheduled};}
function decode(v){
  if(!v||typeof v!=="object")throw new Error("Unsupported Firestore value");
  if("nullValue"in v)return null;
  if("booleanValue"in v)return v.booleanValue;
  if("integerValue"in v)return Number(v.integerValue);
  if("doubleValue"in v)return v.doubleValue;
  if("timestampValue"in v)return new Date(v.timestampValue).toISOString();
  if("stringValue"in v)return v.stringValue;
  if("bytesValue"in v)return v.bytesValue;
  if("referenceValue"in v)return v.referenceValue;
  if("geoPointValue"in v)return v.geoPointValue;
  if("arrayValue"in v)return(v.arrayValue.values??[]).map(decode);
  if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields??{}).map(([k,x])=>[k,decode(x)]));
  throw new Error("Unsupported Firestore value");
}
export async function listFirestoreClinics({fetchImpl,token}){const docs=[];let page="";do{const url=new URL(`${ROOT}/clinics`);url.searchParams.set("pageSize","1000");if(page)url.searchParams.set("pageToken",page);const r=await fetchImpl(url,{headers:{authorization:`Bearer ${token}`}});assert(r.ok,`authoritative inventory failed: HTTP ${r.status}`);const b=await r.json();docs.push(...(b.documents??[]).map(raw=>({id:raw.name.split("/").at(-1),updateTime:raw.updateTime,fields:Object.fromEntries(Object.entries(raw.fields??{}).map(([k,v])=>[k,decode(v)])),raw})));page=b.nextPageToken??"";}while(page);return docs;}
async function main(){const o=parseOptions(process.argv.slice(2)),token=process.env.FIREBASE_ACCESS_TOKEN;assert(token,"set FIREBASE_ACCESS_TOKEN for authenticated dry-run inventory");const read=p=>readFile(new URL(`../${p}`,import.meta.url),"utf8").then(JSON.parse),backup=o.backupPath??`build/backups/firestore-before-hk-clinic-hours-v3-${new Date().toISOString().replaceAll(":","-")}.json`;console.log(JSON.stringify(await runMigration({options:o,readJSON:read,listClinics:()=>listFirestoreClinics({fetchImpl:fetch,token}),writeBackup:d=>writeBackupFile(d,backup),commit:({writes})=>fetch(`${ROOT}:commit`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({writes})})})));}if(process.argv[1]===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e.message);process.exitCode=1;});
